<?php
require_once __DIR__ . '/_bootstrap.php';
$user = require_admin();
$messages = [];
$errors = [];

function admin_config_file(): string { return dirname(__DIR__) . '/config/app.php'; }
function admin_config_contents(array $values): string {
    $export = fn($v) => var_export((string)$v, true);
    $exportBool = fn($v) => ((int) $v === 1 ? 'true' : 'false');
    return "<?php\n" .
        "// Generated by RookGPT admin settings on " . date('c') . ".\n" .
        "defined('DB_HOST') || define('DB_HOST', " . $export(DB_HOST) . ");\n" .
        "defined('DB_NAME') || define('DB_NAME', " . $export(DB_NAME) . ");\n" .
        "defined('DB_USER') || define('DB_USER', " . $export(DB_USER) . ");\n" .
        "defined('DB_PASS') || define('DB_PASS', " . $export(DB_PASS) . ");\n" .
        "defined('AI_PROVIDER') || define('AI_PROVIDER', " . $export($values['ai_provider']) . ");\n" .
        "defined('AI_BASE_URL') || define('AI_BASE_URL', " . $export($values['ai_base_url']) . ");\n" .
        "defined('AI_MODEL') || define('AI_MODEL', " . $export($values['ai_model']) . ");\n" .
        "defined('AI_API_KEY') || define('AI_API_KEY', " . $export($values['ai_api_key']) . ");\n" .
        "defined('OLLAMA_URL') || define('OLLAMA_URL', AI_BASE_URL);\n" .
        "defined('OLLAMA_MODEL') || define('OLLAMA_MODEL', AI_MODEL);\n" .
        "defined('STRIPE_SECRET_KEY') || define('STRIPE_SECRET_KEY', " . $export($values['stripe_secret_key']) . ");\n" .
        "defined('TEAMS_REQUIRE_2FA') || define('TEAMS_REQUIRE_2FA', " . $exportBool($values['teams_require_2fa']) . ");\n" .
        "defined('APP_NAME') || define('APP_NAME', " . $export($values['app_name']) . ");\n" .
        "defined('APP_TAGLINE') || define('APP_TAGLINE', " . $export($values['app_tagline']) . ");\n";
}

if (is_post()) {
        $values = [
            'ai_provider' => strtolower(trim((string)($_POST['ai_provider'] ?? rook_ai_provider_key()))),
            'ai_base_url' => trim((string)($_POST['ai_base_url'] ?? rook_ai_endpoint())),
            'ai_model' => trim((string)($_POST['ai_model'] ?? rook_ai_model())),
            'ai_api_key' => trim((string)($_POST['ai_api_key'] ?? rook_ai_api_key())),
            'stripe_secret_key' => trim((string)($_POST['stripe_secret_key'] ?? (defined('STRIPE_SECRET_KEY') ? STRIPE_SECRET_KEY : ''))),
            'teams_require_2fa' => isset($_POST['teams_require_2fa']) ? 1 : 0,
            'app_name' => trim((string)($_POST['app_name'] ?? APP_NAME)),
            'app_tagline' => trim((string)($_POST['app_tagline'] ?? (defined('APP_TAGLINE') ? APP_TAGLINE : 'Professional AI assistant'))),
        ];
        $providers = rook_ai_providers();
        if (!isset($providers[$values['ai_provider']])) $errors[] = 'Choose a supported AI provider.';
        if ($values['ai_base_url'] === '' || !preg_match('#^https?://#i', $values['ai_base_url'])) $errors[] = 'Enter a valid AI endpoint URL.';
        if ($values['ai_model'] === '') $errors[] = 'Enter an AI model.';
        if (isset($providers[$values['ai_provider']]) && !empty($providers[$values['ai_provider']]['needs_key']) && $values['ai_api_key'] === '') $errors[] = $providers[$values['ai_provider']]['name'] . ' needs an API key.';
        if ($values['app_name'] === '') $errors[] = 'Enter an app name.';
        if (!$errors) {
            $config = admin_config_contents($values);
            if (file_put_contents(admin_config_file(), $config, LOCK_EX) === false) $errors[] = 'Could not write config/app.php. Check file permissions.';
            else { $messages[] = 'Settings saved. Reload pages to pick up the latest constants.'; log_admin_action((int)$user['id'], 'settings.update', 'config', null, 'Updated app/AI provider/Stripe/Teams settings'); }
        }
}

$cfgStripe = defined('STRIPE_SECRET_KEY') ? STRIPE_SECRET_KEY : '';
$teamsRequire2fa = defined('TEAMS_REQUIRE_2FA') ? (bool) TEAMS_REQUIRE_2FA : true;
admin_header('Settings', $user, 'settings');
?>
<div class="admin-card mb-3"><h1 class="h3 mb-1">Settings</h1><p class="text-white-50 mb-0">Update domain-safe runtime settings, AI provider and billing keys without editing PHP files.</p></div>
<?php foreach ($messages as $msg): ?><div class="alert alert-success"><?= e($msg) ?></div><?php endforeach; ?>
<?php foreach ($errors as $err): ?><div class="alert alert-danger"><?= e($err) ?></div><?php endforeach; ?>
<form method="post" class="admin-card vstack gap-3">
  <input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>">
  <div class="row g-3">
    <div class="col-md-6"><label class="form-label">App name</label><input class="form-control" name="app_name" value="<?= e(APP_NAME) ?>"></div>
    <div class="col-md-6"><label class="form-label">Tagline</label><input class="form-control" name="app_tagline" value="<?= e(defined('APP_TAGLINE') ? APP_TAGLINE : 'Professional AI assistant') ?>"></div>
    <?php $providers = rook_ai_providers(); $currentProvider = rook_ai_provider_key(); ?>
    <div class="col-md-4"><label class="form-label">AI provider</label><select class="form-control" id="ai_provider" name="ai_provider"><?php foreach ($providers as $key => $provider): ?><option value="<?= e($key) ?>" data-endpoint="<?= e($provider['endpoint']) ?>" data-model="<?= e($provider['model']) ?>" data-needs-key="<?= !empty($provider['needs_key']) ? '1' : '0' ?>" <?= $currentProvider === $key ? 'selected' : '' ?>><?= e($provider['name']) ?></option><?php endforeach; ?></select></div>
    <div class="col-md-8"><label class="form-label">AI API endpoint</label><input class="form-control" id="ai_base_url" name="ai_base_url" value="<?= e(rook_ai_endpoint()) ?>"></div>
    <div class="col-md-6"><label class="form-label">AI model</label><select class="form-control" id="ai_model" name="ai_model" data-current="<?= e(rook_ai_model()) ?>"><option value="<?= e(rook_ai_model()) ?>" selected><?= e(rook_ai_model()) ?></option></select></div>
    <div class="col-md-6"><label class="form-label">AI API key</label><input class="form-control" type="password" id="ai_api_key" name="ai_api_key" value="<?= e(rook_ai_api_key()) ?>" placeholder="Leave blank for Ollama"></div>
    <div class="col-12 d-flex gap-2 flex-wrap align-items-center"><button class="btn btn-outline-light" type="button" id="fetchModelsBtn"><i class="fa-solid fa-cloud-arrow-down me-1"></i> Test key & fetch models</button><span class="text-white-50" id="modelFetchStatus"></span></div>
    <div class="col-12"><label class="form-label">Stripe secret key</label><input class="form-control" type="password" name="stripe_secret_key" value="<?= e($cfgStripe) ?>" placeholder="sk_test_... or sk_live_..."><div class="form-text text-white-50">Leave blank to keep Stripe checkout disabled until later.</div></div>
    <div class="col-12">
      <div class="form-check form-switch p-3 ps-5 rounded-4 border border-light border-opacity-10" style="background:rgba(255,255,255,.04);">
        <input class="form-check-input" type="checkbox" role="switch" id="teams_require_2fa" name="teams_require_2fa" value="1" <?= $teamsRequire2fa ? 'checked' : '' ?>>
        <label class="form-check-label fw-bold" for="teams_require_2fa">Require 2FA for /teams/</label>
        <div class="form-text text-white-50">When enabled, Business users must set up two-factor authentication before they can open Teams. Turn it off to allow Teams access without 2FA.</div>
      </div>
    </div>
  </div>
  <button class="btn btn-rook align-self-start" type="submit">Save settings</button>
</form>

<script>
(() => {
  const provider = document.getElementById('ai_provider');
  const endpoint = document.getElementById('ai_base_url');
  const model = document.getElementById('ai_model');
  const key = document.getElementById('ai_api_key');
  const btn = document.getElementById('fetchModelsBtn');
  const status = document.getElementById('modelFetchStatus');
  const csrf = document.querySelector('input[name="csrf_token"]')?.value || '';
  function write(message, ok = true) { status.className = ok ? 'text-success fw-bold' : 'text-danger fw-bold'; status.textContent = message; }
  function setModelOptions(models, preferred = '') {
    const keep = preferred || model.value || model.dataset.current || '';
    model.innerHTML = '';
    const list = Array.from(new Set((models || []).filter(Boolean)));
    if (keep && !list.includes(keep)) list.unshift(keep);
    if (!list.length) list.push('');
    list.forEach((name) => {
      const option = document.createElement('option');
      option.value = name;
      option.textContent = name || 'Select a model';
      model.appendChild(option);
    });
    model.value = list.includes(keep) ? keep : list[0];
    model.dataset.current = model.value;
  }
  function fillModels(models) {
    const autoPick = (!model.value || model.dataset.auto === '1');
    setModelOptions(models, autoPick ? ((models || [])[0] || model.value) : model.value);
    if ((models || []).length && autoPick) model.dataset.auto = '1';
  }
  provider?.addEventListener('change', () => { const opt = provider.options[provider.selectedIndex]; endpoint.value = opt.dataset.endpoint || endpoint.value; setModelOptions([opt.dataset.model || model.value], opt.dataset.model || model.value); model.dataset.auto = '1'; key.placeholder = opt.dataset.needsKey === '1' ? 'Required for this provider' : 'Leave blank for Ollama'; write('', true); });
  model?.addEventListener('change', () => { model.dataset.auto = '0'; model.dataset.current = model.value; });
  async function fetchModels(silent = false) {
    if (!silent) { btn.disabled = true; btn.dataset.original = btn.innerHTML; btn.innerHTML = '<i class="fa-solid fa-spinner fa-spin me-1"></i> Checking provider...'; }
    try {
      const body = new URLSearchParams({csrf_token: csrf, provider: provider.value, endpoint: endpoint.value, api_key: key.value});
      const res = await fetch('ai-models', {method:'POST', headers:{'Content-Type':'application/x-www-form-urlencoded'}, body});
      const data = await res.json();
      if (!res.ok || !data.ok) throw new Error(data.error || 'Could not fetch models.');
      fillModels(data.models || []);
      write('Connected. Loaded ' + (data.models || []).length + ' model' + ((data.models || []).length === 1 ? '' : 's') + '.');
    } catch (err) { if (!silent) write(err.message || 'Could not fetch models.', false); }
    finally { if (!silent) { btn.disabled = false; btn.innerHTML = btn.dataset.original || '<i class="fa-solid fa-cloud-arrow-down me-1"></i> Test key & fetch models'; } }
  }
  function canAutoFetch() { const opt = provider.options[provider.selectedIndex]; return endpoint.value && (opt.dataset.needsKey !== '1' || key.value.trim().length > 8); }
  btn?.addEventListener('click', () => fetchModels(false));
  key?.addEventListener('blur', () => { if (canAutoFetch()) fetchModels(false); });
  endpoint?.addEventListener('blur', () => { if (canAutoFetch()) fetchModels(false); });
  provider?.addEventListener('change', () => { setTimeout(() => { if (canAutoFetch()) fetchModels(true); }, 50); });
})();
</script>
<?php admin_footer(); ?>
